export const _expenses = [
    { label: 'Claimed Amount', key: 'claimed_amount' },
    { label: 'Reported Amount', key: 'reported_amount' },
    { label: 'Settled Amount', key: 'claim_settled_amount' },
    { label: 'Deduction Amount', key: 'deduction_amount' },
    // { label: 'Disallowed Amount', key: 'disallowed_amount' },
]

export const _charges = [
    { label: 'Billed Amount', key: 'billed_amount' },
    { label: 'Claim Approved Amount', key: 'claim_approved_amount' },
    { label: 'Claim Settled Amount', key: 'claim_settled_amount' },
    { label: 'Claim Incurred Amount', key: 'claim_incurred_amount' },
    { label: 'Post Hospital Amount', key: 'post_hospital_amount' },
    { label: 'Pre Hospital Amount', key: 'pre_hospital_amount' },
    { label: 'Room Rent charges', key: 'room_rent_charges' },
    { label: 'Surgery charges', key: 'surgery_charges' },
    { label: 'Consulation Charges', key: 'consultation_charges' },
    { label: 'Medicine Charges', key: 'medicine_charges' },
    { label: 'Investigation Charges', key: 'investigation_charges' },
    { label: 'Domicilary Charges', key: 'domiciliary_hospital_amount' },
    { label: 'ICU Amount', key: 'icu_amount' },
    { label: 'ICU Related Amount', key: 'icu_related_amount' },
    { label: 'Nursing Amount', key: 'nursing_amount' },
    { label: 'Health Checkup Amount', key: 'health_checkup_amount' },
    { label: 'Maternity Amount', key: 'maternity_amount' },
    { label: 'Daycare Amount', key: 'daycare_amount' },
    { label: 'Organ Donar Amount', key: 'organ_donor_amount' },
    { label: 'Ancilary Service Amount', key: 'ancillary_service_amount' },
    { label: 'Dental Amount', key: 'dental_amount' },
    { label: 'Out Patient Amount', key: 'out_patient_amount' },
    { label: 'PA Amount', key: 'pa_amount' },
    { label: 'CI Amount', key: 'ci_amount' },
    { label: 'TDS Amount', key: 'tds_amount' },
    { label: 'Service Tax', key: 'service_tax' },
    { label: 'Copayment Amount', key: 'copayment_amount' },
    { label: 'Professional Charges', key: 'professional_charges' },
    { label: 'OT Charges', key: 'OT_charges' },
]
