export * from './submit-claim/SubmitClaim';
export * from './intimate-claim/Intimate';
export * from './track-claim/Track';
export * from './portal-claim/PortalClaim';
export * from './tpa-status-keyword/TpaStatusConfig';
export * from './claim-data/OverAllClaim';
export * from './claim-data/Claim-details-view';
export * from './claim-data/Claim-details-view2';
export * from './deficiency-resolution/DeficiencyResolution'
export * from "./portal-claim/view-claim";
